name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build x86_64
        uses: docker/build-push-action@v3
        if: github.event_name == 'pull_request'
        with:
          context: .
          platforms: linux/amd64
          load: true
      - name: Build arm64
        uses: docker/build-push-action@v3
        if: github.event_name == 'pull_request'
        with:
          context: .
          platforms: linux/arm64
          load: true
      - name: Try to upload to Docker
        uses: docker/build-push-action@v3
        if: github.event_name == 'push'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-docker-builder:latest
